site_name: Cartologic
site_url: http://www.cartologic.com/
repo_url: https://github.com/cartologic/cartoview
site_description: GIS Web Mapping Applications.Cartoview enables the rapid deployment of easy-to-manage and easy-to-use spatial web applications
copyright: Cartologic
site_author: Cartologic
remote_branch: master
remote_name: io
pages:
    -  Cartoview:
        - 'About': 'index.md'
        - 'Key Features': 'key_features.md'
        - 'Demos': 'demo.md'
        - 'Installation - ubuntu': 'installation_ubuntu.md'
        - 'Installation - windows': 'installation_windows.md'
        - 'Installation - docker': 'installation_docker.md'
        - 'Installation - vagrant': 'installation_vagrant.md'
        - 'Install App': 'market.md'
        - 'Developers': 'developers.md'
        - 'Upload App to App Market': 'upload_to_app_market.md'
        - 'Contribute': 'contrib.md'
        - 'Frequently Asked Questions': 'QA.md'
        - 'Issues': 'issues.md'


theme: 'material'
extra:
  palette:
    primary: 'blue'
    accent: 'indigo'
  font:
    text: 'PT Sans'
    code: 'Source Code Pro'

markdown_extensions:
  - admonition
  - footnotes
  - codehilite(linenums=true)
  - toc(permalink=true)
  - meta
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
#  - pymdownx.emoji:
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
